### ISSUE TITLE
Add cargo fmt check to CI

### ISSUE THREAD

**Issue by andygolay** [movementlabsxyz/movement#1195]
Right now there's not a check in CI for `cargo fmt`.

Add one, such as 

```
fmt:
  name: Cargo Format Check
  runs-on: ubuntu-latest

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Run cargo fmt
      run: |
        nix develop --command bash -c "cargo fmt --all -- --check"
```
